#!/bin/sh

export XDG_SESSION_TYPE="x11"
export GDK_BACKEND=x11

[ -f "$HOME/.config/X11/xresources" ] && xrdb -load "$HOME/.config/X11/xresources"

# For the nvidia cards
xrandr --setprovideroutputsource modesetting NVIDIA-0

# setxkbmap -option caps:escape &
# xset s off -dpms &
# xset r rate 200 50 &

[ -f "$HOME/.config/X11/xmodmap" ] && xmodmap "$HOME/.config/X11/xmodmap"

session="${1:-i3}"

case "$session" in
    i3 | awesome) setmonitor; exec "$session";;
    gnome)        exec gnome-session;;
    kde)          exec startplasma-x11;;
    xfce)         exec startxfce4;;
    cinnamon)     exec cinnamon-session;;
    *)            exec "$session";;
esac
