#!/bin/sh

xrdb -load ~/.config/X11/xresources

# For nvidia people
xrandr --setprovideroutputsource modesetting NVIDIA-0

# local scripts
setmonitor &
#setwallpaper &

numlockx &
setxkbmap -option caps:escape &
xset s off -dpms &
xset r rate 300 50 &
/usr/lib/geoclue-2.0/demos/agent &
redshift &
xcompmgr &

# mpd server
[ ! -s ~/.config/mpd/pid ] && mpd &
[[ -z $(pgrep -xU $UID mpdscribble) ]] && mpdscribble &

session="${1:-i3}"

case "$session" in
  i3)     exec i3;;
  bspwm)  exec bspwm;;
  *)      exec "$1";;
esac
