#!/bin/sh

xrdb -load ~/.config/X11/xresources

# For nvidia people
xrandr --setprovideroutputsource modesetting NVIDIA-0

# local scripts
setmonitor &
# setwallpaper &

numlockx &
setxkbmap -option caps:escape &
xset s off -dpms &
xset r rate 300 50 &
/usr/lib/geoclue-2.0/demos/agent &

for p in redshift picom dunst mpd mpdscribble; do
  pidof -s "$p" ||
   if [ "$p" = "picom" ]; then
     "$p" --experimental-backends &
   else
     "$p" &
   fi
done

session="${1:-i3}"

case "$session" in
  i3)     exec i3;;
  bspwm)  exec bspwm;;
  *)      exec "$1";;
esac
