[colors.cursor]
cursor = "#7cafc2"
text = "CellBackground"

[colors.normal]
black   = "#131313"
red     = "#c87e78"
green   = "#b3c48a"
yellow  = "#f7ca88"
blue    = "#7cafc2"
magenta = "#ba8baf"
cyan    = "#86c1b9"
white   = "#d8d8d8"

[colors.bright]
black   = "#585858"
red     = "#ab4642"
green   = "#a1b56c"
yellow  = "#f7ca88"
blue    = "#7cafc2"
magenta = "#ba8baf"
cyan    = "#86c1b9"
white   = "#f8f8f8"

[colors.primary]
background        = "#0f0f0f"
foreground        = "#d8d8d8"
dim_foreground    = "#a0a0a0"

[colors.selection]
background = "#3e4451"
text = "CellForeground"

[cursor]
blink_interval = 500
blink_timeout = 0

[cursor.style]
blinking = "Always"
shape = "Block"

[font]
size = 16.0

[font.normal]
family = "monospace"
style = "Regular"

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
action = "Copy"
hyperlinks = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`)]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "ArrowUp"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "ArrowDown"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[105;5u"
key = "I"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[111;5u"
key = "O"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[79;6u"
key = "O"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[72;6u"
key = "H"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[76;6u"
key = "L"
mods = "Control|Shift"

[mouse]
hide_when_typing = true

[window]
class = "Alacritty"
dynamic_padding = true
# instance = "Alacritty"
opacity = 1.0
title = "Alacritty"

[window.dimensions]
columns = 80
lines = 28
