[colors.cursor]
# cursor = "#4fa6ed"
cursor = "#8195ca"
text = "CellBackground"

[colors.normal]
black   = "#0a0a0a"
blue    = "#8195ca"
cyan    = "#65f1d4"
green   = "#69e49c"
# magenta = "#db4a91"
magenta = "#ec85b1"
red     = "#fb7573"
white   = "#787878"
yellow  = "#eec780"

# [colors.normal]
# black   = "#14171c"
# blue    = "#4fa6ed"
# cyan    = "#48b0bd"
# green   = "#8ebd6b"
# magenta = "#bf68d9"
# red     = "#e55561"
# white   = "#7a818e"
# yellow  = "#e2b86b"

[colors.bright]
black   = "#5c6370"
red     = "#e06c75"
green   = "#98c379"
yellow  = "#ecce85"
blue    = "#61afef"
magenta = "#c678dd"
cyan    = "#56b6c2"
white   = "#ffffff"

[colors.primary]
background = "#0a0a0a"
foreground = "#cecece"

# [colors.primary]
# background = "#14171c"
# foreground = "#abb2bf"

[colors.selection]
background = "#323232"
text = "CellForeground"

[cursor]
blink_interval = 500
blink_timeout = 0

[cursor.style]
blinking = "Always"
shape = "Block"

[font]
size = 16.0

[font.normal]
family = "monospace"
style = "Regular"

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
action = "Copy"
hyperlinks = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "K"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "J"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[105;5u"
key = "I"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[111;5u"
key = "O"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[79;6u"
key = "O"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[72;6u"
key = "H"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[76;6u"
key = "L"
mods = "Control|Shift"

[mouse]
hide_when_typing = true

[window]
class = "Alacritty"
dynamic_padding = true
# instance = "Alacritty"
opacity = 1.0
title = "Alacritty"

[window.dimensions]
columns = 80
lines = 28
