#!/bin/sh
# File copied directly from lf's github wiki page

draw() {
  ~/.config/lf/draw "$@"
  exit 1
}

hash() {
  printf '%s/.cache/lf/%s' "$HOME" \
    "$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | awk '{print $1}')"
}

cache() {
  if [ -f "$1" ]; then
    draw "$@"
  fi
}

file="$1"
shift

case "$(file --mime-type --brief --dereference -- "$file")" in
  text/* | application/json) bat -p -f "$file";;
  audio/*) mediainfo "$file" || exit 1 ;;

  image/*)
    orientation="$(identify -format '%[EXIF:Orientation]\n' -- "$file")"
    if [ -n "$orientation" ] && [ "$orientation" != 1 ]; then
      cache="$(hash "$file").jpg"
      cache "$cache" "$@"
      convert -- "$file" -auto-orient "$cache"
      draw "$cache" "$@"
    else
      draw "$file" "$@"
    fi;;

  video/*)
    cache="$(hash "$file").jpg"
    cache "$cache" "$@"
    ffmpegthumbnailer -i "$file" -o "$cache" -s 0
    draw "$cache" "$@";;

  # */pdf)
  #   cache="$(hash "$file").jpg"
  #   cache "$cache" "$@"
  #   pdftoppm -jpeg -f 1 -singlefile "$file" "$cache"
  #   draw "$cache" "$@";;

  *) echo "Lol, work in progress";;
esac

file -Lb -- "$1" | fold -s -w "$width"
exit 0
