#!/usr/bin/env sh

# My personal Lutris, lol

TITLE=$(echo "${0##*/}" | tr '[:lower:]' '[:upper:]')

games_dir="$HOME/media/emu"

if [ ! -d "$games_dir" ] || [ -n "$(find "$games_dir" -type d -empty)" ]; then
  notify-send -u critical "$TITLE" "O arquivo de jogos não existe!"
  exit 1
fi

plat_sel=$(
  find -L "$games_dir" -maxdepth 1 -mindepth 1 -type d -exec basename '{}' \; |
  rofi -dmenu -i -p ">" -mesg "Choose a platform"
)

[ -z "$plat_sel" ] && exit

game_sel=$(
  find -L "$games_dir/$plat_sel" -type f \
  \( -name "*.zip" -or -name "*.bin" -or -name "*.iso" \) \
  -exec basename '{}' \; |
  sort | rofi -dmenu -i -p ">" -mesg "Choose a game"
)

[ -z "$game_sel" ] && exit

case "$plat_sel" in
  snes) snes9x-gtk "$games_dir/$plat_sel/$game_sel" > /dev/null 2>&1;;
  ps1) duckstation-qt "$games_dir/$plat_sel/$game_sel" > /dev/null 2>&1;;
  ps2) pcsx2-qt "$games_dir/$plat_sel/$game_sel" > /dev/null 2>&1;;
  psp) PPSSPPSDL "$games_dir/$plat_sel/$game_sel" > /dev/null 2>&1;;
  *) notify-send -u critial "$TITLE" "Nenhum emulador para essa plataforma no momento" && exit 1;;
esac
