#!/usr/bin/env sh

[ ! -x "$(command -v rofi)" ] && notify-send "Rofi is not installed" && exit 1

INPUT=$(
  echo "|||" |\
  rofi -dmenu -sep "|" -theme "$HOME/.config/rofi/themes/power.rasi"
)

# In case you are not using systemd
if [ -x "$(command -v systemctl)" ]; then
  sleep() { systemctl suspend ;}
else
  sleep() { sudo loginctl suspend ;}
fi

case "$INPUT" in
  ) sleep;;
  ) sudo poweroff;;
  ) sudo reboot;;
  ) xdotool key Control_L+Alt_L+BackSpace;;
esac
