#!/usr/bin/env sh

# Lil script for starting redshift on login
# and automatic location based on gps

lat_long=$(
    curl -s "https://ipinfo.io/json" |
        jq -r '.loc | split(",") | "\(.[0]):\(.[1])"'
)

if [ "$XDG_SESSION_TYPE" = "wayland" ];then
    [ ! -x "$(command -v gammastep)" ] && exit
    gammastep -l "$lat_long"
    exit
fi

[ ! -x "$(command -v redshift)" ] && exit

redshift -l "$lat_long"
