#!/usr/bin/env sh

hdmi_monitor_width=$(xrandr --listmonitors | awk 'NR==2 {print $3}' | grep -o "^[0-9]\+")

case "$hdmi_monitor_width" in
    2560) width="$hdmi_monitor_width" ;;
    *)    width=1920;;
esac

xrandr \
    --dpi 123 \
    --output "HDMI-0" --mode "${width}x1080" --rate 75 --primary \
    --output "eDP-1-1" --auto --right-of "HDMI-0"
