#!/usr/bin/env sh
# Depends on: xwallpaper, xorg-xrandr, pywal and imagemagick

# Wallpapers directory
wp_dir="$HOME/.local/share/backgrounds"
[ ! -d "$wp_dir" ] && mkdir -p "$wp_dir"

# If there is no image on directory, make one with imagemagick
if [ -n "$(find "$wp_dir" -type d -empty)" ]; then
  # magick -size "$(xrandr | awk '$0 ~ "*" {print $1}' | head -n 1)" canvas:"#5C6370" \
  magick -size "100x56" xc: +noise Random "/tmp/noise.png" &&
  convert "/tmp/noise.png" -virtual-pixel tile -blur 0x18 -auto-level -resize 1920x1080 \
  "${wp_dir}/default.png"
fi

# Set image from argument or default directory
case "$1" in
  "") image=$(find "$wp_dir" -type f \( -name \*.jpg -o -name \*.png \)| shuf -n 1);;
  *)  image=$(readlink -f "$1");;
esac

# Pywal
# [ "$(which wal)" ] && wal -n -s -q -i "$image"

# Get monitors connected
monitors=$(xrandr -q | grep -e '\sconnected')

# If there is only one monitor connected
[ "$(echo "$monitors" | wc -l)" -eq 1 ] && \
  xwallpaper --output "$(echo "$monitors" | cut -d" " -f1)" --stretch "$image" && exit

# Dual monitor setup
printf "%s\n" "$monitors" |
while IFS= read -r m; do
  case $m in
    *primary*)
      xwallpaper --output "$(echo "$m" | cut -d" " -f1)" --stretch "$image";;
    *)
      xwallpaper --output "$(echo "$m" | cut -d" " -f1)" --zoom "$image";;
  esac
done

