#!/bin/sh

# Editor alias
[ -x "$(command -v nvim)" ] && alias vim="nvim"
[ -x "$(command -v emacs)" ] && alias emacs="emacsclient -nc -a emacs"

# Verbose commands
alias \
  mv="mv -iv" \
  cp="cp -iv" \
  rm="rm -Iv" \
  rmdir="rmdir -v" \
  mkdir="mkdir -pv" \
  stow="stow -v" \
  ln="ln -v"

# ls command
alias \
  ls="ls -X --color=auto --group-directories-first" \
  la="ls -A" \
  ll="ls -lh"

# Color output
alias \
  grep="grep --color=auto" \
  diff="diff --color=auto" \
  ip="ip -color=auto"

# Arch Linux
[ -x "$(command -v pacman)" ] &&
alias \
  pacup="sudo pacman -Syu && yay -Sua --noconfirm --removemake"

# Void Linux
[ -x "$(command -v xbps-install)" ] &&
alias \
  xi="sudo xbps-install" \
  xq="xbps-query" \
  xr="sudo xbps-remove" \
  xall="sudo xbps-install -Su && xcheckrestart"

# General stuff
alias \
  du="du -h" \
  tree="tree -a -C" \
  hist="fc -l 1" \
  so="source ~/.config/zsh/.zshrc" \
  fale="espeak -v roa/pt-BR" \
  c="clear" \
  rsync="rsync --info=progress2" \
  hx="helix" \
  cwd="pwd | xclip -r -sel clip" \
  anom=" unset HISTFILE" \
  cleaner="rm .pulse-cookie .steampath" \
  ffmpeg="ffmpeg -hide_banner -loglevel info" \
  ffprobe="ffprobe -hide_banner" \
  mount.droid="mkdir ~/android; simple-mtpfs --device 1 ~/android" \
  umount.droid="fusermount -u ~/android && rmdir ~/android" \
  open="xdg-open"

# Apps
alias \
  sxiv="nsxiv -b -a" \
  zt="zathura" \
  play="aplay -D pipewire"
  # mpv="mpv --hwdec=auto --autofit=60%x60% --fs" \

# System
alias \
  off="sudo poweroff" \
  reboot="sudo reboot" \
  suspend="sudo systemctl suspend"

# Git
alias \
  gs="git status" \
  ga="git add" \
  gc="git commit" \
  gl="git log --stat" \
  gd="git diff" \
  gp="git push" \
  gb="git branch"

# Clean home aliases
alias \
  nvidia-settings='nvidia-settings --config="$XDG_CONFIG_HOME"/nvidia/settings' \
  yarn='yarn --use-yarnrc $XDG_CONFIG_HOME/yarn/config'
