#!/usr/bin/env sh

# Arguments:
#   $1: path to image file
#   $2: image width
#   $3: image height

s="  " # field separator

exec 2>/dev/null

filename=$(basename -- "$1")
filesize=$(du -Hh -- "$1" | cut -f 1)
geometry="${2}x${3}"

tmp_dir=$(find /tmp -type d \( -name "34get*" -or -name "rofi-34*" \))
if [ -z "$tmp_dir" ]; then
  echo "${filename}${s}${filesize}${s}${geometry}"
else
  json_file=$(find "$tmp_dir" -type f -name "json-info")
  hash="${filename%.*}"
  tags="$(jq -r '.[]? | select(.hash == "'"$hash"'") | .tags' < "$json_file")"
  echo "${filename}${s}${tags}" && exit
fi


