#!/usr/bin/env sh

while read -r file; do
  case "$1" in
    "b") setwallpaper "$file";;
    "i") notify-send "Info" "$(file "$file")";;
    "m") mor-handler "$file";;
    "d") rm "$file" && notify-send "SXIV" "$file\nfoi removido";;
  esac
done
