#!/usr/bin/env bash

# A scrpit for editing config files

# Text editor of preference
#EDITOR="vim"

# Array with config files location
declare -a options=(
"alacritty $HOME/.config/alacritty/alacritty.yml"
"bashrc $HOME/.bashrc"
"bash_profile $HOME/.bash_profile"
"i3 $HOME/.config/i3/config"
"i3blocks $HOME/.config/i3blocks/i3blocks.conf"
"i3status $HOME/.config/i3status/i3status.conf"
"mpd $HOME/.config/mpd/mpd.conf"
"ncmpcpp $HOME/.config/ncmpcpp/config"
"picom $HOME/.config/picom/picom.conf"
"polybar $HOME/.config/polybar/config.ini"
"vim $HOME/.vimrc"
"xinitrc $HOME/.xinitrc"
"zshrc $HOME/.zshrc"
"zsh_profile $HOME/.zprofile"
"quit"
)

# Display array on dmenu
choice=$(printf '%s\n' "${options[@]}" | dmenu -i -l 20 -p 'Edit config')

# If quit is selected, exit
if [[ "$choice" == "quit" ]]; then
	echo "Finalizado" && exit 1

# Print the selected option and awk to get the last column
# And open the config with the editor
elif [ "$choice" ]; then
	choosen=$(printf '%s\n' "${choice}" | awk '{print $NF}')
	$EDITOR "$choosen"

# Exit the program
else
	echo "Finalizado" && exit 1
fi
